spring:
  application:
    name: sequence-tutorial

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:sequence_tutorial;MODE=MYSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER"
    username: sequence
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    open-in-view: false

server:
  port: 8080

jwt:
  header: Authorization
  issuer: sequence
  clientSecret: FJEIOWFJKLjFl3r4109fue0
  expirySeconds: 10000